name = "vibescale"
compatibility_date = "2025-04-04"
main = "./src/server/index.ts"

[dev]
ip = "0.0.0.0"


[durable_objects]
bindings = [
  { class_name = "VibescaleServer", name = "VIBESCALE" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "VibescaleServer" ]

[observability]
enabled = true

[assets]
  directory = "./dist"
  binding = "ASSETS"
  not_found_handling = "single-page-application"